[package]
name = "turbo-picard-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Picard-compatible command-line entrypoint for turbo-picard."
default-run = "turbo-picard"

[[bin]]
name = "turbo-picard"
path = "src/main.rs"

[[bin]]
name = "picard"
path = "src/bin/picard.rs"

[dependencies]
rust-htslib.workspace = true
hts-sys.workspace = true
md5.workspace = true
flate2.workspace = true
rustc-hash.workspace = true
crossbeam-channel.workspace = true
turbo-picard-core = { path = "../turbo-picard-core", version = "0.1.11" }
turbo-picard-markdup = { path = "../turbo-picard-markdup", version = "0.1.11" }
tempfile.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
predicates.workspace = true
