rule build_bam_index:
    input:
        bam="results/{sample}.bam"
    output:
        bai="results/{sample}.bam.bai"
    shell:
        "turbo-picard BuildBamIndex I={input.bam} O={output.bai}"


rule sort_sam:
    input:
        bam="results/{sample}.bam"
    output:
        bam="results/{sample}.sorted.bam"
    shell:
        "turbo-picard SortSam I={input.bam} O={output.bam} SORT_ORDER=coordinate"


rule mark_duplicates:
    input:
        bam="results/{sample}.bam"
    output:
        bam="results/{sample}.marked.bam",
        metrics="results/{sample}.metrics.txt"
    shell:
        "turbo-picard MarkDuplicates I={input.bam} O={output.bam} M={output.metrics} ASSUME_SORTED=true VALIDATION_STRINGENCY=SILENT"


rule sam_to_fastq:
    input:
        bam="results/{sample}.bam"
    output:
        fastq="results/{sample}.fastq"
    shell:
        "turbo-picard SamToFastq I={input.bam} FASTQ={output.fastq}"


rule sam_to_fastq_per_rg:
    input:
        bam="results/{sample}.bam"
    output:
        per_rg=directory("results/{sample}.rg-fastq")
    params:
        rg_tag="PU"
    shell:
        "turbo-picard SamToFastq I={input.bam} OUTPUT_PER_RG=true RG_TAG={params.rg_tag} OUTPUT_DIR={output.per_rg}"


rule fastq_to_sam:
    input:
        r1="results/{sample}_R1.fastq.gz",
        r2="results/{sample}_R2.fastq.gz"
    output:
        bam="results/{sample}.unmapped.bam"
    params:
        read_group=lambda wildcards: f"{wildcards.sample}-rg",
        use_sequential_fastqs="false"
    shell:
        "turbo-picard FastqToSam FASTQ={input.r1} FASTQ2={input.r2} OUTPUT={output.bam} SAMPLE_NAME={wildcards.sample} READ_GROUP_NAME={params.read_group} USE_SEQUENTIAL_FASTQS={params.use_sequential_fastqs}"


rule fix_mate_information:
    input:
        bam="results/{sample}.bam"
    output:
        bam="results/{sample}.fixed.bam",
        bai="results/{sample}.fixed.bai"
    shell:
        "turbo-picard FixMateInformation I={input.bam} O={output.bam} CREATE_INDEX=true"
