[package]
name = "turbo-picard-markdup"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Native accelerated MarkDuplicates engine for turbo-picard."

[dependencies]
turbo-picard-core = { path = "../turbo-picard-core", version = "0.1.13" }
md5.workspace = true
regex.workspace = true
rust-htslib.workspace = true
rustc-hash.workspace = true
tempfile.workspace = true
thiserror.workspace = true
