[package]
name = "turbo-picard-markdup"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Native accelerated MarkDuplicates engine for turbo-picard."

[dependencies]
turbo-picard-core = { path = "../turbo-picard-core", version = "0.1.1" }
md5 = "0.8.0"
rust-htslib = "1.0.0"
rustc-hash = "1.1.0"

[dev-dependencies]
tempfile = "3.23.0"
