import tempfile
import unittest
from pathlib import Path
import sys
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parent))
import compare_real_data


class CompareRealDataTests(unittest.TestCase):
    def test_sam_record_digest_ignores_headers(self):
        with tempfile.TemporaryDirectory() as tmp:
            first = Path(tmp) / "first.sam"
            second = Path(tmp) / "second.sam"
            first.write_text(
                "@HD\tVN:1.6\n@SQ\tSN:chr1\tLN:100\nread-a\t0\tchr1\t1\t60\t4M\t*\t0\t0\tACGT\tFFFF\n",
                encoding="utf-8",
            )
            second.write_text(
                "@HD\tVN:1.5\n@PG\tID:picard\nread-a\t0\tchr1\t1\t60\t4M\t*\t0\t0\tACGT\tFFFF\n",
                encoding="utf-8",
            )

            self.assertEqual(
                compare_real_data.digest_sam_records(first),
                compare_real_data.digest_sam_records(second),
            )

    def test_sam_record_digest_ignores_optional_tag_order(self):
        with tempfile.TemporaryDirectory() as tmp:
            first = Path(tmp) / "first.sam"
            second = Path(tmp) / "second.sam"
            first.write_text(
                "@HD\tVN:1.6\n"
                "read-a\t0\tchr1\t1\t60\t4M\t*\t0\t0\tACGT\tFFFF\tMD:Z:4\tNM:i:0\tRG:Z:1\n",
                encoding="utf-8",
            )
            second.write_text(
                "@HD\tVN:1.6\n"
                "read-a\t0\tchr1\t1\t60\t4M\t*\t0\t0\tACGT\tFFFF\tRG:Z:1\tNM:i:0\tMD:Z:4\n",
                encoding="utf-8",
            )

            self.assertEqual(
                compare_real_data.digest_sam_records(first),
                compare_real_data.digest_sam_records(second),
            )

    def test_stable_text_digest_ignores_comments_and_blank_lines(self):
        with tempfile.TemporaryDirectory() as tmp:
            first = Path(tmp) / "first.txt"
            second = Path(tmp) / "second.txt"
            first.write_text("# generated by Picard\n\nA\tB\n1\t2\n", encoding="utf-8")
            second.write_text("# generated by turbo-picard\nA\tB\n1\t2\n\n", encoding="utf-8")

            self.assertEqual(
                compare_real_data.digest_stable_text(first),
                compare_real_data.digest_stable_text(second),
            )

    def test_capture_version_accepts_picard_nonzero_version_output(self):
        completed = mock.Mock(returncode=1, stdout="Version:3.4.0\n")
        with mock.patch.object(compare_real_data.subprocess, "run", return_value=completed):
            self.assertEqual(compare_real_data.capture_version(["picard", "ViewSam", "--version"]), "Version:3.4.0")

    def test_input_metadata_can_record_source_citation(self):
        with tempfile.TemporaryDirectory() as tmp:
            input_bam = Path(tmp) / "input.bam"
            input_bam.write_bytes(b"bam")

            metadata = compare_real_data.input_metadata(
                input_bam,
                "https://github.com/samtools/htslib/blob/abc/test/range.bam",
                "abc",
            )

            self.assertEqual(metadata["source_url"], "https://github.com/samtools/htslib/blob/abc/test/range.bam")
            self.assertEqual(metadata["source_commit"], "abc")

    def test_manifest_entry_is_generated_from_passing_evidence(self):
        summary = {
            "parity": "PASS",
            "input": {
                "path": "benchmarks/real-data/example/input.bam",
                "sha256": "a" * 64,
                "source_url": "https://github.com/example/repo/blob/abc/input.bam",
                "source_commit": "abc",
            },
            "commands": [
                {
                    "command": "ViewSam",
                    "status": "PASS",
                    "comparison": "SAM record digest",
                },
                {
                    "command": "CleanSam",
                    "status": "FAIL",
                    "comparison": "post-command SAM record digest",
                },
            ],
        }

        entry = compare_real_data.build_manifest_entry(
            summary=summary,
            dataset_id="example",
            evidence_json=Path("benchmarks/real-data/example/real-data-comparison.json"),
            evidence_markdown=Path("benchmarks/real-data/example/real-data-comparison.md"),
            scope_caveat="larger public shard",
            release_tier="release_candidate",
        )

        self.assertEqual(entry["id"], "example")
        self.assertEqual(entry["release_tier"], "release_candidate")
        self.assertEqual(entry["sha256"], "a" * 64)
        self.assertEqual(entry["source_commit"], "abc")
        self.assertEqual(entry["expected_commands"], {"ViewSam": "SAM record digest"})

    def test_manifest_entry_requires_source_citation(self):
        summary = {
            "parity": "PASS",
            "input": {"path": "input.bam", "sha256": "a" * 64},
            "commands": [],
        }

        with self.assertRaises(SystemExit):
            compare_real_data.build_manifest_entry(
                summary=summary,
                dataset_id="missing-citation",
                evidence_json=Path("evidence.json"),
                evidence_markdown=Path("evidence.md"),
                scope_caveat="missing citation",
                release_tier="public_smoke",
            )

    def test_manifest_entry_rejects_failing_comparison(self):
        summary = {
            "parity": "FAIL",
            "input": {
                "path": "input.bam",
                "sha256": "a" * 64,
                "source_url": "https://github.com/example/repo/blob/abc/input.bam",
                "source_commit": "abc",
            },
            "commands": [],
        }

        with self.assertRaises(SystemExit):
            compare_real_data.build_manifest_entry(
                summary=summary,
                dataset_id="failed",
                evidence_json=Path("evidence.json"),
                evidence_markdown=Path("evidence.md"),
                scope_caveat="failed",
                release_tier="public_smoke",
            )

    def test_markduplicates_semantic_digest_ignores_incidental_tags(self):
        with tempfile.TemporaryDirectory() as tmp:
            first = Path(tmp) / "first.sam"
            second = Path(tmp) / "second.sam"
            first.write_text(
                "@HD\tVN:1.6\n"
                "@SQ\tSN:chr1\tLN:100\n"
                "read-a\t1024\tchr1\t1\t60\t4M\t=\t10\t100\tACGT\tFFFF\tPG:Z:picard\tDT:Z:LB\n",
                encoding="utf-8",
            )
            second.write_text(
                "@HD\tVN:1.6\n"
                "@SQ\tSN:chr1\tLN:100\n"
                "read-a\t1024\tchr1\t1\t60\t4M\t=\t10\t100\tACGT\tFFFF\tPG:Z:turbo\tDT:Z:LB\n",
                encoding="utf-8",
            )

            self.assertNotEqual(
                compare_real_data.digest_sam_records(first),
                compare_real_data.digest_sam_records(second),
            )
            self.assertEqual(
                compare_real_data.digest_markduplicates_semantics(first),
                compare_real_data.digest_markduplicates_semantics(second),
            )


if __name__ == "__main__":
    unittest.main()
