#!/usr/bin/env python3
"""Append or replace a real-data evidence entry in the checked manifest."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import verify_real_data_evidence


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MANIFEST = ROOT / "benchmarks" / "real-data" / "manifest.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge a comparator manifest-entry.json into benchmarks/real-data/manifest.json.",
    )
    parser.add_argument(
        "--entry",
        required=True,
        type=Path,
        help="Path to manifest-entry.json generated by tools/compare_real_data.py.",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help="Manifest path to update.",
    )
    parser.add_argument(
        "--replace",
        action="store_true",
        help="Replace an existing dataset with the same id instead of refusing it.",
    )
    return parser.parse_args()


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def merge_entry(manifest: dict, entry: dict, *, replace: bool = False) -> dict:
    if "datasets" not in manifest:
        manifest = {**manifest, "datasets": []}
    if not isinstance(manifest["datasets"], list):
        raise ValueError("manifest datasets must be a list")
    dataset_id = entry.get("id")
    if not isinstance(dataset_id, str) or not dataset_id:
        raise ValueError("manifest entry missing non-empty id")

    merged_datasets = []
    replaced = False
    for dataset in manifest["datasets"]:
        if dataset.get("id") != dataset_id:
            merged_datasets.append(dataset)
            continue
        if not replace:
            raise ValueError(
                f"dataset id already exists: {dataset_id} (use --replace to update it)"
            )
        merged_datasets.append(entry)
        replaced = True

    if not replaced:
        merged_datasets.append(entry)
    return {**manifest, "datasets": merged_datasets}


def write_manifest(path: Path, manifest: dict) -> None:
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    args = parse_args() if argv is None else parse_args_from(argv)
    try:
        manifest = load_json(args.manifest)
        entry = load_json(args.entry)
        merged = merge_entry(manifest, entry, replace=args.replace)
        errors = verify_real_data_evidence.validate_manifest(merged)
        if errors:
            for error in errors:
                print(error, file=sys.stderr)
            return 1
        write_manifest(args.manifest, merged)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(error, file=sys.stderr)
        return 1
    print(f"updated {args.manifest}")
    return 0


def parse_args_from(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge a comparator manifest-entry.json into benchmarks/real-data/manifest.json.",
    )
    parser.add_argument("--entry", required=True, type=Path)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--replace", action="store_true")
    return parser.parse_args(argv)


if __name__ == "__main__":
    raise SystemExit(main())
